### ISSUE TITLE
Doprax

### ISSUE THREAD

**Issue by t-e-s-tweb** [wy580477/Mosdns-on-PaaS#3]
Hey can you please make a tutorial for it on dropax? I tried but can't get it to work.

**Comment by wy580477** [comment]
Show me your deployment log and runtime log.

**Comment by wy580477** [comment]
> I get bad gateway error on opening and setting the URL.

Did you set HTTP port to 8080 during deployment？

**Comment by wy580477** [comment]
> It's already set in docker file. Also I set both the environment variables DOH_PATH /dns-query and PORT 8080.

Emm..... I think it's likely a problem due to high load on Doprax servers.

![image](https://user-images.githubusercontent.com/98247050/215252602-ec8f2316-9a85-4fed-af06-2949b3860dc6.png)

**Comment by wy580477** [comment]
> Well the other app that you screenshoted, I use that too but never had any issue with that at all.

Some servers has higher load than others.

![image](https://user-images.githubusercontent.com/98247050/215252811-63dbde00-0260-42fb-bd2c-096bd61a871d.png)

I will test it later.

**Comment by wy580477** [comment]
> Well the other app that you screenshoted, I use that too but never had any issue with that at all.

Doprax website is totally unusable now. I tried with two different accout, both failed to import Github repo....

**Comment by wy580477** [comment]
> It works on okteto, railway and koyeb. I wanted to run it on dropax because my latency is lowest to their servers so it's fast.

I can't help you, Doprax is totally unusable for me now.
